---
- name: Change Router Configuration
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Set Paramiko Python interpreter
      set_fact:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
      run_once: true
      
    - name: Change IP address
      ios_command:
        commands:
          - configure terminal
          - interface GigabitEthernet2
          - ip address 192.168.56.1 255.255.255.0
          - no shutdown
          - exit

    - name: Change hostname
      ios_command:
        commands:
          - configure terminal
          - hostname R1
          - exit

    - name: Save configuration
      ios_command:
        commands:
          - write memory
