---
- name: Change Router Configuration
  hosts: routers
  gather_facts: false
  connection: local

  tasks:
    - name: Change IP address
      ios_command:
        commands:
          - configure terminal
          - interface GigabitEthernet2
          - ip address 192.168.56.1 255.255.255.0
          - no shutdown
          - exit

    - name: Change hostname
      ios_command:
        commands:
          - configure terminal
          - hostname R1
          - exit

    - name: Save configuration
      ios_command:
        commands:
          - write memory
